### ISSUE TITLE
Konstruktion der Multisearch über Konfigurations-Datei

### ISSUE THREAD

**Issue by ltog** [linked-swissbib/vufind#11]

**Comment by PhilippKuntschik** [comment]
Commit https://github.com/linked-swissbib/vufind/commit/42cbeb9c786b1c54a9fc69c893d469366b195e65 introduces the first step in using multisearch. There were only two steps done here: 1. override the `$params['body']` and 2. call `msearch` instead of `search`. **A very important detail is that this search string HAS to end with a newline.**

As the code introduced in this commit represents a working communication between vufind and elasticsearch, it is possible to investigate further on two ends: building the request and parsing the response. Following my former observations that might help:
- the event bus hits the first line of code introduced by swissbib at [Results.php#L58](https://github.com/linked-swissbib/vufind/blob/feature/multisearch/module/LinkedSwissbib/src/LinkedSwissbib/Search/Elasticsearch/Results.php#L58). If you want to investigate everything via debugging use this as a starting point.
- This was called by [AbstractSearch.php#L225](https://github.com/linked-swissbib/vufind/blob/vfsb/linked/module/VuFind/src/VuFind/Controller/AbstractSearch.php#L225) which -- if i see this correct -- hooks the async search to the view (as in MVC)
- The elasticsearch pipeline implemented by swissbib basically starts with [Backend.search()](https://github.com/linked-swissbib/vufind/blob/vfsb/linked/module/LinkedSwissbib/src/LinkedSwissbib/Backend/Elasticsearch/Backend.php#L84).The construction and processing of the esDSLQuery starts here. I think this is also a good starting point for adjusting the search query to our needs.
- To this point, I don't know exactly how the received data is parsed into an php-object, but i think it should be somewhere in [Elasticsearch/Response/](https://github.com/linked-swissbib/vufind/tree/vfsb/linked/module/LinkedSwissbib/src/LinkedSwissbib/Backend/Elasticsearch/Response)

**Comment by PhilippKuntschik** [comment]
Some further investigation revealed that the parsing process indeed starts with [RecordCollectionFactory.php#L77](https://github.com/linked-swissbib/vufind/blob/vfsb/linked/module/LinkedSwissbib/src/LinkedSwissbib/Backend/Elasticsearch/Response/RecordCollectionFactory.php#L77). With multisearch it will be necessary to a) standardize the searchqueries (first the author, then her work) or b) to keep a reference to the used search query somewhere as the received array now has the form [response]**[responses][INTEGER]**[hits][hits].

As I don't know yet if a reference to the used searchquery would be thread-safe, i vote for standardizing the searchquery. One way or another, This RecordCollectionFactory is the place where the php-object gets parsed.
