### ISSUE TITLE
Definition of fields to search

### ISSUE THREAD

**Issue by ltog** [linked-swissbib/vufind#9]
@guenterh 

I'm referring to http://localhost/sbrd/Exploration/Author?lookfor=hello . I do not understand where we define,  in which fields (e.g. `foaf:lastName` or `rdfs:label`) we want to search.

I would like to adjust this for the `ExploreAuthor` controller.

**Comment by guenterh** [comment]
Hi Lukas, I will give you a response in the course of this morning

**Comment by guenterh** [comment]
@ltog @marahellstern 

Hi Lukas,
if you are going to use the request
http://localhost/vflinked/Exploration/authorDetails?lookfor=johann%20wolfgang%20goethe&type=Contributor
the Backend will create a query against ES using the defined search for Contributor in 
https://github.com/linked-swissbib/vufind/blob/vfsb/linked/local/config/vufind/searchspecsES.yaml

Only the fields for the embedded contributor will be used. Not the additional ones defined for AllFields.

You can debug this mechanism 
https://github.com/linked-swissbib/vufind/blob/vfsb/linked/module/LinkedSwissbib/src/LinkedSwissbib/Backend/Elasticsearch/Backend.php#L104

My aim is to use phpUnit Tests for this. Therefor the Travis integration I have done yesterday for the two VuFind projects under the github domains of swissbib and linked-swissbib. But I need more time to finsh this methods and complete the infrastructure.

Back to your question how to define a request for authors:
the proposal lookfor=johann%20wolfgang%20goethe&type=Contributor is just one alternative. Another possibility would be to use something like  
http://localhost/vflinked/Exploration/authorDetails?name=wolfgang Goethe
where the controller could have the knowledge to set the missing Type parameter for the backend. I think we should go for the moment with one of several alternatives. Otherwise we will get lost....

The problem for you (Chur) at the moment is, that we are still working heavily providing the necessary data (Genf, Köln, Basel). Things are changing and/or evolving constantly. But we have to cope with it. 

Günter

@sschuepbach for info
